Resources:
  pipelinePolicyAAFB625F:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetObject*
              - s3:GetBucket*
              - s3:List*
              - s3:DeleteObject*
              - s3:PutObject*
              - s3:Abort*
            Effect: Allow
            Resource:
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":s3:::"
                    - Fn::ImportValue: CodeArtifactsBucket
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":s3:::"
                    - Fn::ImportValue: CodeArtifactsBucket
                    - /*
          - Action: sts:AssumeRole
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - PipelineFailsLambdaInvokeActionCodePipelineActionRole4C4821EB
                - Arn
        Version: "2012-10-17"
      PolicyName: pipelinePolicyAAFB625F
      Roles:
        - Fn::Select:
            - 1
            - Fn::Split:
                - /
                - Fn::Select:
                    - 5
                    - Fn::Split:
                        - ":"
                        - Fn::ImportValue: CodePipelineRole
  PipelineC660917D:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn:
        Fn::ImportValue: CodePipelineRole
      Stages:
        - Actions:
            - ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: "1"
              Configuration:
                Owner: me
                Repo: repo
                Branch: master
                OAuthToken: something
                PollForSourceChanges: false
              Name: Source
              OutputArtifacts:
                - Name: SourceArtifact
              RunOrder: 1
          Name: Source
        - Actions:
            - ActionTypeId:
                Category: Invoke
                Owner: AWS
                Provider: Lambda
                Version: "1"
              Configuration:
                FunctionName:
                  Fn::Select:
                    - 6
                    - Fn::Split:
                        - ":"
                        - Fn::ImportValue: SomeFunction
              Name: LambdaInvokeAction
              RoleArn:
                Fn::GetAtt:
                  - PipelineFailsLambdaInvokeActionCodePipelineActionRole4C4821EB
                  - Arn
              RunOrder: 1
          Name: Fails
      ArtifactStore:
        Location:
          Fn::ImportValue: CodeArtifactsBucket
        Type: S3
    DependsOn:
      - pipelinePolicyAAFB625F
  PipelineSourceWebhookResourceD1089B44:
    Type: AWS::CodePipeline::Webhook
    Properties:
      Authentication: GITHUB_HMAC
      AuthenticationConfiguration:
        SecretToken: something
      Filters:
        - JsonPath: $.ref
          MatchEquals: refs/heads/{Branch}
      TargetAction: Source
      TargetPipeline:
        Ref: PipelineC660917D
      TargetPipelineVersion: 1
      RegisterWithThirdParty: true
  PipelineFailsLambdaInvokeActionCodePipelineActionRole4C4821EB:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              AWS:
                Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":iam::"
                    - Ref: AWS::AccountId
                    - :root
        Version: "2012-10-17"
  PipelineFailsLambdaInvokeActionCodePipelineActionRoleDefaultPolicy42605B7D:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: lambda:ListFunctions
            Effect: Allow
            Resource: "*"
          - Action: lambda:InvokeFunction
            Effect: Allow
            Resource:
              Fn::ImportValue: SomeFunction
        Version: "2012-10-17"
      PolicyName: PipelineFailsLambdaInvokeActionCodePipelineActionRoleDefaultPolicy42605B7D
      Roles:
        - Ref: PipelineFailsLambdaInvokeActionCodePipelineActionRole4C4821EB

